require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SwagLabsMobileApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # Pods for SwagLabsMobileApp
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'RNQuickAction', :path => '../node_modules/react-native-quick-actions'

  # For the Camera
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
