name: Build

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Build
      run: |
        npm install
        npm run android.release
        find . -name "*.apk"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./android/app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
